/* Generated by tools/generate_runtime_translations.py. Do not edit by hand. */
(function () {
    "use strict";
    window.BattleBrothersJPStrings = window.BattleBrothersJPStrings || {};
    var moduleStrings = {};
    Object.keys(moduleStrings).forEach(function (english) {
        window.BattleBrothersJPStrings[english] = moduleStrings[english];
    });
}());
