/* Generated by tools/generate_runtime_translations.py. Do not edit by hand. */
(function () {
    "use strict";
    window.BattleBrothersJPStrings = window.BattleBrothersJPStrings || {};
    var moduleStrings = {
    "Change Array": "配列を変更",
    "Change Keybind": "キーバインドを変更",
    "Color Picker": "カラーピッカー",
    "Mod Options": "MODオプション",
    "Mod Settings": "MOD設定",
    "OK": "決定",
    "Reset": "リセット",
    "Select a Mod From the List": "一覧からMODを選択"
};
    Object.keys(moduleStrings).forEach(function (english) {
        window.BattleBrothersJPStrings[english] = moduleStrings[english];
    });
}());
